config:
  prefix: !
  UWCS_discord_bridge_bot_id: 1337
  UWCS_member_role_id: 2674
  UWCS_exec_role_ids: [ 9874698723 ]
  UWCS_welcome_channel_id: 420
  UWCS_roles_channel_id: 952926102333042688
  UWCS_exec_spam_channel_id: 1234
  database_connection: "postgresql://apollo:apollo@localhost/apollo"
  UWCS_discord_id: 1337
  UWCS_api_token: api_token
  bot_secret_key: secret_key
  karma_timeout: 900
  discord_token: discord_token
  sql_logging: on
  bot_logging: on
  debug: True     # Unused
  reminder_search_interval: 30
  channel_check_interval: 60
  announcement_search_interval: 60
  announcement_impersonate: True
  slicer_path: /path/to/prusa-slicer
  printer_file_root: /path/to/print/files
